### ISSUE TITLE
download size wrong..

### ISSUE THREAD

**Issue by fengmk2** [cnpm/mirrors#10]
[dist_sync_info] [2015-01-15 20:29:18.706][848] download https://iojs.org/dist/v1.0.0/iojs-v1.0.0-darwin-x64.tar.gz got status 200, headers: {"server":"nginx/1.4.6 (Ubuntu)","date":"Thu, 15 Jan 2015 12:25:43 GMT","content-type":"application/x-gzip","content-length":"6453498","last-modified":"Wed, 14 Jan 2015 03:16:41 GMT","connection":"keep-alive","etag":"\"54b5df99-6278fa\"","strict-transport-security":"max-age=63072000","x-frame-options":"DENY","x-content-type-options":"nosniff","accept-ranges":"bytes"}

[dist_sync_info] [2015-01-15 20:29:18.712][848] uploading /tmp/mirrors_download/848_iojs_v1.0.0_iojs-v1.0.0-darwin-x64.tar.gz to nfs:/dist/iojs/v1.0.0/iojs-v1.0.0-darwin-x64.tar.g

[dist_sync_info] [2015-01-15 20:29:18.844][848] upload /dist/iojs/v1.0.0/iojs-v1.0.0-darwin-x64.tar.gz to nfs:http://oss.npm.taobao.org/dist/iojs/v1.0.0/iojs-v1.0.0-darwin-x64.tar.gz with size:NaN, sha1:32af06715b7132bd9e7a908d796a4114ab9b6b12, md5: e1470c66629aaddb94ca62c228e947a2

[dist_sync_info] [2015-01-15 20:29:18.844][848] Sync dist file: {"name":"iojs-v1.0.0-darwin-x64.tar.gz","date":"14-Jan-2015 03:16","size":769685,"type":"file","parent":"/v1.0.0/","url":"http://oss.npm.taobao.org/dist/iojs/v1.0.0/iojs-v1.0.0-darwin-x64.tar.gz","sha1":"32af06715b7132bd9e7a908d796a4114ab9b6b12","md5":"e1470c66629aaddb94ca62c228e947a2","category":"iojs"} done

**Comment by fengmk2** [comment]
还不是 log 问题，`"content-length":"6453498"` 是 6mb 多，但实际下载才 `"size":769685`

需要增加 content-length 检查

**Comment by dead-horse** [comment]
我和页面上标识的size做过检查的
