### ISSUE TITLE
Mirror Request for nw.js

### ISSUE THREAD

**Issue by evshiron** [cnpm/mirrors#107]
Description:
NW.js (previously known as node-webkit) lets you call all Node.js modules directly from DOM and enables a new way of writing applications with all Web technologies.
Source:
http://dl.nwjs.io/
Note:
Legacy versions before 0.12.3 are delivered by Apache DirectoryIndex, and modern versions are deployed on Amazon S3 (https://nwjs.s3-us-west-2.amazonaws.com/).
There is no HTTPS or signatures to trust the synchronized files. Amazon S3 can be accessed via HTTPS though.
I have written a project [evshiron/nwjs-mirror](https://github.com/evshiron/nwjs-mirror) to synchronize both Apache DirectoryIndex and Amazon S3 files. Maybe it can be used as a reference.

Why?
Because electron is mirrored. People who develop nw.js applications from China mainland should like this, too.

I could do the job and send a PR if there is a need.

**Comment by fengmk2** [comment]
OK, I will config to mirror nw.js from http://dl.nwjs.io/. 

Can I only mirror versions start from `v0.12.0` ?

**Comment by fengmk2** [comment]
Oh no, 0.13.0 dist page is client js render. Sync from s3 only https://nwjs.s3-us-west-2.amazonaws.com/

**Comment by fengmk2** [comment]
- get versions http://nwjs.s3-us-west-2.amazonaws.com/?delimiter=/&prefix=
- get one version http://nwjs.s3-us-west-2.amazonaws.com/?delimiter=/&prefix=v0.16.0/
- x64 http://nwjs.s3-us-west-2.amazonaws.com/?delimiter=/&prefix=v0.16.0/x64/

**Comment by evshiron** [comment]
Yes. It's client rendered.
Accessing directly from https://nwjs.s3-us-west-2.amazonaws.com/ will bring a large amount of garbage. The usage of `delimiter` and `prefix` is cool, and it's used in `evshiron/nwjs-mirror`.
But as nw.js 0.12.3 is previous LTS version, I assume there is a need for it (for example DingTalk).

**Comment by fengmk2** [comment]
v0.12.3 is store on s3 too http://nwjs.s3-us-west-2.amazonaws.com/?delimiter=/&prefix=v0.12.3/

**Comment by evshiron** [comment]
BTW see also http://nwjs.io/versions.json, it includes all nw.js versions supposed to be used.

**Comment by evshiron** [comment]
@fengmk2 That's an excellent discovery. Then we can only synchronize with Amazon S3.

**Comment by fengmk2** [comment]
sync tests running https://cnpmjs.org/mirrors/nwjs/v0.12.0-alpha1/

**Comment by evshiron** [comment]
@fengmk2 LGTM :)

**Comment by evshiron** [comment]
Hey @fengmk2, according to the title "Mirror index of http://nwjs.s3-us-west-2.amazonaws.com/", it looks like you are using HTTP and I recommend using HTTPS instead if possible.

**Comment by fengmk2** [comment]
nwjs on taobao npm now https://npm.taobao.org/mirrors/nwjs/

**Comment by evshiron** [comment]
@fengmk2 Roger. Thanks!
