### ISSUE TITLE
mirror imagemin series

### ISSUE THREAD

**Issue by e-cloud** [cnpm/mirrors#126]
imagemin的二进制包都从github下载，经常挂掉，能不能支持对应镜像？

**Comment by fengmk2** [comment]
@e-cloud 如何重现？安装那个模块？

**Comment by e-cloud** [comment]
安装 image-webpack-loader

**Comment by fengmk2** [comment]
@e-cloud cnpm 是安装 image-webpack-loader 都是走镜像下载的，不知道你的问题是什么。

![image](https://cloud.githubusercontent.com/assets/156269/20957397/84202390-bc8a-11e6-9d72-0b457f71bd8f.png)

**Comment by e-cloud** [comment]
不好意思，我这边用的是npm或者yarn，只是在 https://npm.taobao.org/mirrors 上面没看到对应的镜像列表，以为不支持。有非 cnpm 的配置吗？

**Comment by fengmk2** [comment]
@e-cloud 这些代理没你想象中那么简单 https://github.com/cnpm/binary-mirror-config/blob/master/package.json#L115 ，目前是 npminstall 做的，npm 和 yarn 都无法搞定。

**Comment by e-cloud** [comment]
好，明白了，只能这些库本身提供镜像支持才行，它们现在都是hardcode github 资源地址的。

**Comment by fengmk2** [comment]
是的，无法通过参数或者环境变量解决，所以npm和yarn都搞不定
