### ISSUE TITLE
git-for-windows 镜像与官方不同步

### ISSUE THREAD

**Issue by gucong3000** [cnpm/mirrors#129]
https://github.com/git-for-windows/git/releases/download/v2.11.0.windows.1/Git-2.11.0-64-bit.exe

如上，官方地址可下载，镜像未更新

**Comment by fengmk2** [comment]
明明有的啊 https://npm.taobao.org/mirrors/git-for-windows/2.11.0.windows.1/

**Comment by gucong3000** [comment]
@fengmk2 
同步有延迟么？
首次访问时同步的么？

**Comment by fengmk2** [comment]
不是的，每5分钟检测更新并同步的，下次发现安装失败，请将详细日志提供一下。
