### ISSUE TITLE
git-for-windows url 与官方有差异

### ISSUE THREAD

**Issue by gucong3000** [cnpm/mirrors#131]
官网的
https://github.com/git-for-windows/git/releases/download/v2.11.0.windows.1/Git-2.11.0-32-bit.exe

cnpm的
https://npm.taobao.org/mirrors/git-for-windows/2.11.0.windows.1/Git-2.11.0-32-bit.exe

两个url，cnpm的，少一个字母"v"，这会导致设置镜像为cnpm时下载失败

比如这种脚本就会报错 #130

**Comment by fengmk2** [comment]
脚本改一下不就行了？

**Comment by gucong3000** [comment]
仔细想了下，确实可以改，官方拿到的最新git tag，删除一个字母v，就可以了。
但是感觉有点脏。

只是个不太强烈的建议，改不改你们做主。

**Comment by gucong3000** [comment]
@fengmk2 吐槽一下，url略坑啊，正式版本一律干掉了字母v，其他的都在
所以如果要使用cnpm镜像下载git，脚本中不能简单的使用字符串拼接来完成啊。需要些逻辑来去掉字母v

```
// 官方源，有字母v
https://github.com/git-for-windows/git/releases/download/prerelease-v2.11.0.windows.1.1/
// 官方源，有字母v
https://github.com/git-for-windows/git/releases/download/v2.11.0.windows.1/Git-2.11.0-32-bit.exe"
// cnpm源，无字母v
https://npm.taobao.org/mirrors/git-for-windows/2.11.0.windows.1/Git-2.11.0-64-bit.exe
// cnpm源，有字母v
https://npm.taobao.org/mirrors/git-for-windows/prerelease-v2.11.0.windows.1.1/Git-prerelease-2.11.0.rc0.windows.2-64-bit.exe
```

**Comment by gucong3000** [comment]
```
var url = asset.browser_download_url;
var mirror = process.env.GIT_FOR_WINDOWS_MIRROR;
if(mirror) {
    mirror = mirror.replace(/\/*$/, '/');
    if(mirror.indexOf('npm.taobao.org') > 0) {
        url = url.replace(/^.+?\/download\/v?/, mirror);
    } else {
        url = url.replace(/^.+?\/download\//, mirror);
    }
}
```

这样一来，cnpm需要特殊处理呢

**Comment by gucong3000** [comment]
这个问题，我的脚本可以改，但其他使用git-for-windows镜像的人就没法安装成功了。

**Comment by gucong3000** [comment]
这个问题还是建议改一下，因为github官方在release创建页面会建议用户在release名称前加前缀`v`
另外，还有node-pre-gyp-github生成的release名称也带`v`
这个逻辑应该是公共的吧？我期望改的不是某个库的地址，而是期望所有镜像github release地址的库，都与官方一致

**Comment by gucong3000** [comment]
终于找到问题所在了
未处理这种情况
https://npm.taobao.org/mirrors/git-for-windows/prerelease-v2.11.0.windows.1.1/Git-prerelease-2.11.0.rc0.windows.2-64-bit.exe

https://github.com/cnpm/mirrors/blob/master/sync/GithubWithVersion.js#L27

**Comment by fengmk2** [comment]
https://cnpmjs.org/mirrors/git-for-windows/v2.14.1.windows.1/ 重新在跑了

**Comment by gucong3000** [comment]
我了个擦，还是不对啊
https://npm.taobao.org/mirrors/git-for-windows/v2.10.0.windows.1/Git-2.10.0-64-bit.exe
404

https://github.com/git-for-windows/git/releases/download/v2.11.0.windows.1/Git-2.11.0-64-bit.exe
正常

**Comment by gucong3000** [comment]
看起来GithubWithVersion这个类，是重新组装出来的url啊，并非根据原始的url“换头”而来

**Comment by gucong3000** [comment]
@fengmk2 
新数据都OK了，但是貌似老数据没有更新
https://npm.taobao.org/mirrors/git-for-windows/
![image](https://user-images.githubusercontent.com/1171691/29303992-30f1f442-81c3-11e7-8c79-fbd11e59852d.png)

**Comment by fengmk2** [comment]
老数据不会动了，只更新最近的10个版本。

**Comment by gucong3000** [comment]
OK
