### ISSUE TITLE
node 源未与官方同步

### ISSUE THREAD

**Issue by gucong3000** [cnpm/mirrors#134]
在使用nvm切换node版本时，发现有几个URL未与官方同步
http://npm.taobao.org/mirrors/node/v7.6.0/node-v7.6.0-linux-x64.tar.xz
http://npm.taobao.org/mirrors/node/v7.6.0/node-v7.6.0.tar.xz
http://npm.taobao.org/mirrors/node/v6.10.0/node-v6.10.0-linux-x64.tar.xz
http://npm.taobao.org/mirrors/node/v6.10.0/node-v6.10.0.tar.xz

**Comment by fengmk2** [comment]
今天同步量有点大，已经全部同步好了。
