### ISSUE TITLE
mirror atom-shell 缺失 SHASUMS256.txt 文件

### ISSUE THREAD

**Issue by fishbar** [cnpm/mirrors#141]
checksum 用到的两个文件目前没有同步， sync/atom-shell.js 需要修复这个bug

文件例子：
```
https://npm.taobao.org/mirrors/atom-shell/v1.6.4/SHASUMS256.txt
```

**Comment by fishbar** [comment]
验证是否生效的方法：

1.  创建目录test,  test目录中新建 package.json
```
tnpm i --save electron-rebuild
tnpm i --save microtime
```
安装最新版即可

2. cd到test目录中，调用electron-rebuild：
```
./node_modules/.bin/electron-rebuild -d=https://npm.taobao.org/mirrors/atom-shell
```
成功执行说明ok， 报错则检查提示。


---
线上貌似已经同步了checksum需要的文件，我本地跑通了。

**Comment by fengmk2** [comment]
fixed by https://github.com/cnpm/mirrors/pull/142
