### ISSUE TITLE
atom-shell一直没有更新

### ISSUE THREAD

**Issue by gera2ld** [cnpm/mirrors#147]
<https://npm.taobao.org/mirrors/atom-shell/>的atom-shell一直没有更新（找不到v1.3.15），而<https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/index.json>这个文件是更新了的。

**Comment by fengmk2** [comment]
https://npm.taobao.org/mirrors/atom-shell/v1.3.5/

**Comment by gera2ld** [comment]
@fengmk2 是 **1.3.15** 不是 **1.3.5** 。。新机器第一次用atom或者更新的时候必然挂在这上面。
已经用代理解决了，镜像经常掉链子
