### ISSUE TITLE
收录GraphicsMagick

### ISSUE THREAD

**Issue by yaniswang** [cnpm/mirrors#149]
官方仓库：ftp://ftp.graphicsmagick.org/pub/GraphicsMagick/1.3/

http://78.108.103.11/MIRROR/ftp/GraphicsMagick/
这个镜像更快一点

**Comment by fengmk2** [comment]
好了 https://ftp.mirror.cnpmjs.org/MIRROR/ftp/GraphicsMagick/1.3/
