### ISSUE TITLE
npm syncer

### ISSUE THREAD

**Issue by fengmk2** [cnpm/mirrors#15]
https://github.com/npm/npm/tags
https://github.com/hakobera/nvmw/pull/36

**Comment by fengmk2** [comment]
https://github.com/npm/npm/archive/v2.0.0.zip

**Comment by fengmk2** [comment]
https://api.github.com/repos/npm/npm/releases

**Comment by dead-horse** [comment]
哈哈，这个太方便了，搞个 github 的 syncer，然后把 atom-shell / node-webkit 全部搞下来，不过这个接口有访问次数限制的吧

**Comment by fengmk2** [comment]
30分钟请求一次。。。

**Comment by dead-horse** [comment]
可以申请 key 的吧

**Comment by dead-horse** [comment]
https://developer.github.com/v3/#rate-limiting

**Comment by dead-horse** [comment]
- atom-shell
- nw.js
- wrk

**Comment by fengmk2** [comment]
https://api.github.com/repos/npm/npm/releases got 200, {"server":"GitHub.com","date":"Sat, 17 Jan 2015 16:09:22 GMT","content-type":"application/json; charset=utf-8","transfer-encoding":"chunked","status":"200 OK","x-ratelimit-limit":"60","x-ratelimit-remaining":"55","x-ratelimit-reset":"1421514208","cache-control":"public, max-age=60, s-maxage=60","etag":"W/\"d9407b4331e766159d819431ef8f0b20\"","vary":"Accept, Accept-Encoding","x-github-media-type":"github.v3","link":"<https://api.github.com/repositories/321278/releases?page=2>; rel=\"next\", <https://api.github.com/repositories/321278/releases?page=3>; rel=\"last\"","x-xss-protection":"1; mode=block","x-frame-options":"deny","content-security-policy":"default-src 'none'","access-control-allow-credentials":"true","access-control-expose-headers":"ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval","access-control-allow-origin":"*","x-github-request-id":"7AE9E3BD:3E46:689CA3C:54BA8932","strict-transport-security":"max-age=31536000; includeSubdomains; preload","x-content-type-options":"nosniff","x-served-by":"065b43cd9674091fec48a221b420fbb3","content-encoding":"gzip"}
