### ISSUE TITLE
add yarn

### ISSUE THREAD

**Issue by tamascsaba** [cnpm/mirrors#153]
mirror yarn from `https://yarnpkg.com/downloads/`

You can download like offical node Dockerfile:
https://github.com/nodejs/docker-node/blob/4f2354e558a0cd93ae53278f83f5f0a35af23be0/8.2/Dockerfile

**Comment by fengmk2** [comment]
ok, I will add yarn mirror soon.

**Comment by fengmk2** [comment]
all releases can download from github too https://github.com/yarnpkg/yarn/releases

**Comment by tamascsaba** [comment]
@fengmk2 thx you are awesome, It was a really quick commit :+1:

**Comment by fengmk2** [comment]
https://cnpmjs.org/mirrors/yarn/

**Comment by fengmk2** [comment]
China mirror work too https://npm.taobao.org/mirrors/yarn/0.27.5/
