### ISSUE TITLE
nodegit url 与官方不一致

### ISSUE THREAD

**Issue by gucong3000** [cnpm/mirrors#155]
Node 版本：7
```bash
npm install nodegit --nodegit_binary_host_mirror=https://npm.taobao.org/mirrors/nodegit/
```

无法利用上面的命令安装
期望nodegit是https://nodegit.s3.amazonaws.com/ 的镜像

**Comment by gucong3000** [comment]
nodegit 如果改为发布到GitHub releases, 应该就可以通过现有的类`GithubWithVersion`来同步了。
nodegit/nodegit#1353

**Comment by fengmk2** [comment]
http 404 https://npm.taobao.org/mirrors/nodegit/v0.18.3/nodegit-v0.18.3-node-v57-darwin-x64.tar.gz

我看了一下官方的 https://nodegit.s3.amazonaws.com/nodegit/nodegit/v0.18.3/nodegit-v0.18.3-node-v57-darwin-x64.tar.gz 也是 404 啊

**Comment by gucong3000** [comment]
https://travis-ci.org/nodegit/nodegit/jobs/226132802#L6978
看了下发布日志，发布后的url是这样的
https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.18.3-node-v46-linux-x64.tar.gz

**Comment by gucong3000** [comment]
如果nodegit他们能够改为发布到GitHub releases，我们这边应该就好弄多了

**Comment by fengmk2** [comment]
https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.18.3-node-v46-linux-x64.tar.gz 这个是有的 https://npm.taobao.org/mirrors/nodegit/v0.18.3/nodegit-v0.18.3-node-v46-linux-x64.tar.gz，然而 https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.18.3-node-v57-linux-x64.tar.gz 是没有的。

**Comment by gucong3000** [comment]
那是因为nodegit这边的情况是，目前预编译的二进制包，覆盖的平台和node版本比较少。

**Comment by gucong3000** [comment]
我们暂时只讨论本镜像的问题
`https://npm.taobao.org/mirrors/nodegit/v0.18.3/nodegit-v0.18.3-node-v46-linux-x64.tar.gz`这个url，跟官方地址相比，多出了一级目录`/v0.18.3/`，所以用--nodegit_binary_host_mirror参数会安装失败

**Comment by gucong3000** [comment]
```bash
npm install nodegit --nodegit_binary_host_mirror=https://npm.taobao.org/mirrors/nodegit/v0.18.3/
```
这样安装会安装成功


```bash
npm install nodegit --nodegit_binary_host_mirror=https://npm.taobao.org/mirrors/nodegit/
```
这样会安装失败

期望后一个用例能安装成功

**Comment by gucong3000** [comment]
我觉得这个问题最简单的解决方案是让nodegit那边发布到GitHub releases，实在不行的话，我们这边改url，剪掉多出的`/v0.18.3/`

**Comment by gucong3000** [comment]
nodegit新版本发布，已有解决方案，只测试了windows下安装：
```bash
$ npm i --save nodegit --nodegit_binary_host_mirror=https://npm.taobao.org/mirrors/nodegit/v{version}/
```
@fengmk2 我们是否该推进他们在文档中写出通过镜像安装的方法？
nodegit/nodegit#1355
