### ISSUE TITLE
electrom-rebuild 目前在atom-shell中只同步到1.6.5

### ISSUE THREAD

**Issue by advsets** [cnpm/mirrors#166]
官方已经发布到1.8.1-beta了， 目前atom-shell，重建版本只同步到1.6.5， 导致后面的版本无法通过镜像做electron-rebuild , 做C/C++的依赖

**Comment by iunfire** [comment]
![image](https://user-images.githubusercontent.com/8299627/33157285-0ba452d0-d03c-11e7-8b7f-4958c1f14ac8.png)
