### ISSUE TITLE
Add browserstack-local

### ISSUE THREAD

**Issue by tamascsaba** [cnpm/mirrors#186]
It would be fine mirror browserstack-local with cnpm/mirors :) :)

Browserstack-local is avalible on
https://s3.amazonaws.com/browserStack/browserstack-local

More information: 
https://github.com/browserstack/browserstack-local-nodejs/blob/master/lib/LocalBinary.js

**Comment by tamascsaba** [comment]
@fengmk2 ??

**Comment by fengmk2** [comment]
OK, I get it.

**Comment by fengmk2** [comment]
@tamascsaba no version fo browserstack-local files?

**Comment by tamascsaba** [comment]
Unfortunetly browserstack files not avalible in versioned format :(
