### ISSUE TITLE
nwjs 的最新版本缺失

### ISSUE THREAD

**Issue by alsotang** [cnpm/mirrors#208]
比如这个是空的 https://cnpmjs.org/mirrors/nwjs/v0.35.2/

排障过程：
1. 源站问题  https://nwjs2.s3.amazonaws.com/?delimiter=/&prefix=v0.35.2/
源站没问题。有 0.35.2 版本
2. 解析逻辑问题 https://github.com/cnpm/mirrors/blob/583bfffe5c6e50d01056f95fa9c35a2f2769a21d/sync/nw.js 
我试着把 `var fileRe = /<Contents><Key>([^<]+)<\/Key><LastModified>([^<]+)<\/LastModified><ETag>([^<]+)<\/ETag><Size>(\d+)<\/Size><StorageClass>[^<]+<\/StorageClass><\/Contents>/g;` 语句拿出来跑了一下，发现能够正常解析 0.35.2 的页面。
3. 同步问题
目前认为是同步有问题。麻烦维护者看看数据库的情况。

**Comment by fengmk2** [comment]
@alsotang 修正代码，我让同步重新开始即可。

**Comment by alsotang** [comment]
@fengmk2 我的结论是代码不用修啊。代码没问题

**Comment by fengmk2** [comment]
https://cnpmjs.org/mirrors/nwjs/v0.32.1/ 不行，还是要修代码，我让它重新爬取一次还是空的。

**Comment by fengmk2** [comment]
<Contents><Key>v0.35.2/nwjs-sdk-v0.35.2-linux-ia32.tar.gz</Key><LastModified>2018-12-14T01:22:18.000Z</LastModified><ETag>&quot;d700b5e87199e8adf3202af3edac55cf-13&quot;</ETag><Size>104002972</Size><StorageClass>STANDARD</StorageClass></Contents>

**Comment by alsotang** [comment]
感觉本地调试贼困难。我去弄个机器跑起来先解决这个问题，再把测试修好。
再看看怎么搞一套细粒度一点的测试规范，我就为了调试一个nwjs syncer，现在找不到好办法直接去测那个解析逻辑。

**Comment by alsotang** [comment]
我写了一些调试代码测那个解析逻辑，0.35.0 也是好的，还是搭一套起来调试。

**Comment by alsotang** [comment]
fixed by https://github.com/cnpm/mirrors/pull/210
