### ISSUE TITLE
Cypress 镜像路径错误

### ISSUE THREAD

**Issue by jkzing** [cnpm/mirrors#215]
按照官方文档（https://docs.cypress.io/guides/getting-started/installing-cypress.html#Mirroring）

路径应该是：https://www.example.com/desktop/:version?platform=p
实际是：https://npm.taobao.org/mirrors/cypress/3.1.5/osx64/

看到了这个 PR：https://github.com/cnpm/npminstall/pull/270, `npminstall` 里直接 hack 了这个路径...

正常 npm 和 yarn 仍然没法安装...

PS: 可以用写死 `CYPRESS_INSTALL_BINARY`
```sh
CYPRESS_INSTALL_BINARY=https://npm.taobao.org/mirrors/cypress/3.1.5/osx64/cypress.zip npm install
```

**Comment by fengmk2** [comment]
不 hack 无法实现。

**Comment by fengmk2** [comment]
已经解决，使用 cnpm i cypress 即可。

**Comment by abcfy2** [comment]
@fengmk2 是否可以考虑通过URL重写的方式兼容`CYPRESS_DOWNLOAD_MIRROR`方案呢？

比如配置`CYPRESS_DOWNLOAD_MIRROR=https://npm.taobao.org/mirrors/cypress/`

然后将类似于`https://npm.taobao.org/mirrors/cypress/desktop/4.5.0?platform=linux&arch=x64`这种规则重写为`https://npm.taobao.org/mirrors/cypress/4.5.0/linux-x64/cypress.zip`？

我看阿里云的CDN应该支持这种重写规则，无论如何，感谢镜像站的付出。

**Comment by fengmk2** [comment]
@abcfy2   href: 'https://cdn.npm.taobao.org/dist/cypress/7.1.0/darwin-x64/cypress.zip',
我看 cnpm i cypress 还是能下载的啊，走了镜像的。

**Comment by abcfy2** [comment]
> @abcfy2 href: 'https://cdn.npm.taobao.org/dist/cypress/7.1.0/darwin-x64/cypress.zip',
> 我看 cnpm i cypress 还是能下载的啊，走了镜像的。

我是说如果支持URL重写的方式，就可以直接用npm i了，因为`CYPRESS_DOWNLOAD_MIRROR`这个变量是cypress官方安装脚本定义的变量，会将发送请求到类似于这样的地址上: `https://npm.taobao.org/mirrors/cypress/desktop/7.1.0?platform=linux&arch=x64`
