### ISSUE TITLE
nodegit的地址格式与 preinstall 中不对应

### ISSUE THREAD

**Issue by alsotang** [cnpm/mirrors#218]
当执行 `npm install nodegit` 的时候，nodegit 的 preinstall 脚本请求的地址格式如下：

https://cnpmjs.org/mirrors/nodegit/nodegit-v0.24.1-node-v64-darwin-x64.tar.gz

但是 mirrors 这边的 path 多了一个版本号

https://cnpmjs.org/mirrors/nodegit/v0.24.1/nodegit-v0.24.1-node-v64-darwin-x64.tar.gz

这块我的想法是，我这边在node这一层来做个重定向。

**Comment by fengmk2** [comment]
@alsotang 不能的，这样服务端逻辑太多。看看为什么多了这个路径。

**Comment by alsotang** [comment]
@fengmk2 mirrors这边的路径是常见的，因为看起来是从 github release 同步来的。主要是nodegit那边的路径中少了一段。

**Comment by alsotang** [comment]
https://github.com/nodegit/nodegit/blob/977251b4aae52eef75cf4f188b4d5a63ba98fa7b/package.json#L74

https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.24.1-node-v64-darwin-x64.tar.gz

**Comment by fengmk2** [comment]
cnpm i nodegit 没问题啊

```bash
cnpm i nodegit
✔ Installed 1 packages
✔ Linked 139 latest versions
[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN Using request for node-pre-gyp https download
node-pre-gyp
http GET https://cdn.npm.taobao.org/dist/nodegit/v0.24.1/nodegit-v0.24.1-node-v64-darwin-x64.tar.gz
node-pre-gyp
http 200 https://cdn.npm.taobao.org/dist/nodegit/v0.24.1/nodegit-v0.24.1-node-v64-darwin-x64.tar.gz
[nodegit] Success: "/private/tmp/node_modules/_nodegit@0.24.1@nodegit/build/Release/nodegit.node" is installed via remote
[nodegit] Completed installation successfully.

```

**Comment by alsotang** [comment]
`npm i nodegit --nodegit_binary_host_mirror=https://npm.taobao.org/mirrors/nodegit/ --verbose`

```
node-pre-gyp
http GET https://npm.taobao.org/mirrors/nodegit/nodegit-v0.24.1-node-v64-darwin-x64.tar.gz
node-pre-gyp
http 404 https://npm.taobao.org/mirrors/nodegit/nodegit-v0.24.1-node-v64-darwin-x64.tar.gz
```

**Comment by alsotang** [comment]
https://github.com/cnpm/npminstall/pull/71   ????????

**Comment by alsotang** [comment]
看起来好像你当年还专门修过这个nodegit的地址问题

**Comment by alsotang** [comment]
我觉得吧，兼容性问题，越是上游解决就越是麻烦少。当时就应该在 mirrors 地址层面解决这个事情，而不是 npminstall 去下游进行适配。

**Comment by fengmk2** [comment]
应该去改 nodegit ，mirrors 不会单独去适配的。

**Comment by alsotang** [comment]
现在npm配上 nodegit 的 mirrors 的地址无法工作。mirrors的格式应该要以 nodegit 官方的为准吧？

**Comment by fengmk2** [comment]
@alsotang 晕，说了半天，是你配置错误了 https://github.com/cnpm/binary-mirror-config/blob/master/package.json#L128

**Comment by alsotang** [comment]
呃 确实，第一次知道这个语法
