### ISSUE TITLE
Electron 镜像 404

### ISSUE THREAD

**Issue by meowtec** [cnpm/mirrors#231]
Electron v7.0.1

electron 7 开始，二进制文件下载 URL 的格式从

```
https://npm.taobao.org/mirrors/electron/6.1.0/electron-v6.1.0-darwin-x64.zip
```

变成了

```
https://npm.taobao.org/mirrors/electron/v7.0.0/electron-v6.1.0-darwin-x64.zip
```

多了一个 `v`，导致 404

**Comment by Constaline** [comment]
设置一下 ELECTRON_MIRROR="https://cdn.npm.taobao.org/dist/electron/"

**Comment by XmanChai** [comment]
该地址无法访问

**Comment by fengmk2** [comment]
每个 major 最新版本都重新补充了。 https://npm.taobao.org/mirrors/electron/v7.3.3/electron-v7.3.3-darwin-x64.zip
