### ISSUE TITLE
electron-builder-binaries 镜像地址无效

### ISSUE THREAD

**Issue by hzyhbk** [cnpm/mirrors#240]
官网上找到这个
`  ELECTRON_BUILDER_BINARIES_MIRROR=http://npm.taobao.org/mirrors/electron-builder-binaries/ electron-builder build
` 但是打开的地址是无效的，望修复

**Comment by bkkkd** [comment]
我去,竟然一年多还没有维护了.

**Comment by meteormatt** [comment]
现在应该是好的。

**Comment by fengmk2** [comment]
给一个具体有问题的 url ？

**Comment by meowtec** [comment]
https://npmmirror.com/mirrors/electron/11.5.0/electron-v11.5.0-darwin-x64.zip: status code 404

**Comment by fengmk2** [comment]
@meteormatt 地址是 https://npmmirror.com/mirrors/electron/v11.5.0/electron-v11.5.0-darwin-x64.zip

**Comment by fengmk2** [comment]
https://npmmirror.com/mirrors/electron/11.5.0/electron-v11.5.0-darwin-x64.zip 2个路径都兼容了。
