### ISSUE TITLE
mirror prisma

### ISSUE THREAD

**Issue by fjc0k** [cnpm/mirrors#248]
https://github.com/prisma/prisma

https://github.com/prisma/prisma/issues/1333#issuecomment-607868654

https://binaries.prisma.sh/

**Comment by Lxxyx** [comment]
https://cnpmjs.org/mirrors/prisma/

反馈：这边看到 Prisma 的 Mirror 版本是旧的，没有更新，是否可以更新到最新版呢

**Comment by fengmk2** [comment]
https://r.cnpmjs.org/-/binary/prisma/ Please try to this mirror.

**Comment by rojer95** [comment]
> https://r.cnpmjs.org/-/binary/prisma/ Please try to this mirror.

![image](https://user-images.githubusercontent.com/20662049/152286225-c16bd2b9-63cc-4584-8f05-df6d4e89fe56.png)

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/-/binary/prisma/ China mirror worked now.
