### ISSUE TITLE
Lack of mirrors

### ISSUE THREAD

**Issue by Holybasil** [cnpm/mirrors#260]
electron-build --linux

target: ["deb", "rpm"]

cannot resolve https://npm.taobao.org/mirrors/electron-builder-binaries/fpm-1.9.3-20150715-2.2.2-mac/fpm-1.9.3-20150715-2.2.2-mac.7z: status code 404
cannot resolve https://npm.taobao.org/mirrors/electron-builder-binaries/linux-tools-mac-10.12.3/linux-tools-mac-10.12.3.7z: status code 404

**Comment by fengmk2** [comment]
都成功了。
