### ISSUE TITLE
phantomjs 镜像挂了

### ISSUE THREAD

**Issue by superbug** [cnpm/mirrors#282]
## 操作步骤
访问链接：https://npmmirror.com/mirrors/phantomjs

OR 

```shell
curl https://cdn.npmmirror.com/binaries/phantomjs
```

## 错误信息
<img width="870" alt="截屏2022-02-06 下午10 40 56" src="https://user-images.githubusercontent.com/2010627/152686205-96bd8413-9140-4af5-9377-fcbf9cf7f150.png">

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <RequestId>61FFDEA876145431319E76DD</RequestId>
  <HostId>npmmirror.oss-cn-shanghai.aliyuncs.com</HostId>
  <Key>binaries/phantomjs</Key>
</Error>
```

**Comment by fengmk2** [comment]
https://www.npmjs.com/package/phantomjs 已经不再推荐使用，我们也不会再提供镜像服务了。

**Comment by superbug** [comment]
<img width="1185" alt="截屏2022-02-07 上午8 59 36" src="https://user-images.githubusercontent.com/2010627/152709675-3762e85b-f887-4469-b563-bdad56808fed.png">

这些都不再维护了是么？  官网是否可以注明一下？或者把链接下掉？好多链接点开都是上述错误。


Node.js 镜像: [https://npmmirror.com/mirrors/node](https://npmmirror.com/mirrors/node?spm=a2c6h.24755359.0.0.6d446093t3bC1b)
alinode 镜像: [https://npmmirror.com/mirrors/alinode](https://npmmirror.com/mirrors/alinode?spm=a2c6h.24755359.0.0.6d446093t3bC1b)
phantomjs 镜像: https://npmmirror.com/mirrors/phantomjs
ChromeDriver 镜像: https://npmmirror.com/mirrors/chromedriver
OperaDriver 镜像: https://npmmirror.com/mirrors/operadriver
Selenium 镜像: https://npmmirror.com/mirrors/selenium
Node.js 文档镜像: https://npmmirror.com/mirrors/node/latest/docs/api/index.html
NPM 镜像: https://npmmirror.com/mirrors/npm/

@fengmk2

**Comment by fengmk2** [comment]
@superbug 除了 phantomjs 都还在的，路径没有更新，你加一个 / 在 url 最后即可，我晚点会去更新一下。

 phantomjs 你可以使用这个环境变量，历史的数据还在，但是不保证未来持续可用：       "PHANTOMJS_CDNURL": "https://oss.npmmirror.com/dist/phantomjs",

**Comment by fengmk2** [comment]
@superbug 你需要拼接完整 URL 才能下载的 https://npmmirror.com/mirrors/phantomjs/phantomjs-2.1.1-macosx.zip

**Comment by superbug** [comment]
解决了，谢谢~

更新了一波环境变量，一切都好了：

Before：
```
sass_binary_site=https://npm.taobao.org/mirrors/node-sass/
phantomjs_cdnurl=https://npm.taobao.org/mirrors/phantomjs/
canvas_binary_host_mirror=https://npm.taobao.org/mirrors/node-canvas-prebuilt/
```

After：
```
sass_binary_site=https://oss.npmmirror.com/dist/node-sass/
phantomjs_cdnurl=https://oss.npmmirror.com/dist/phantomjs
canvas_binary_host_mirror=https://oss.npmmirror.com/dist/node-canvas-prebuilt/
```

**Comment by fengmk2** [comment]
@superbug oss.npmmirror.com 只是临时过度，不建议你长期使用，后续等数据迁移完我们会下线的，因为这个 oss 服务费用太高，不太可能继续维护下去。你可以使用新的 oss 地址代替的。

```
sass_binary_site=https://cdn.npmmirror.com/binaries/node-sass/
phantomjs_cdnurl=https://cdn.npmmirror.com/binaries/phantomjs/
canvas_binary_host_mirror=https://cdn.npmmirror.com/binaries/canvas/
```
