### ISSUE TITLE
mozjpeg-bin二进制镜像404不存在

### ISSUE THREAD

**Issue by ZhaoTim** [cnpm/mirrors#283]
![image](https://user-images.githubusercontent.com/30540533/152732287-cc84ce9b-9144-4fb0-ad76-f9dba2259634.png)
以前还是好了，过了个春节，突然发现找不到所有的版本了，人傻了。

有大佬帮忙解答一下吗？

**Comment by fengmk2** [comment]
有问题，我看看为什么没有同步成功。

**Comment by fengmk2** [comment]
@ZhaoTim 明天上午再来应该就都好了。

**Comment by ZhaoTim** [comment]
@fengmk2 好的，感谢大佬这么快就修复了！👍🏻👍🏻👍🏻

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/binary.html?path=mozjpeg-bin/ 同步好了。
