### ISSUE TITLE
oss download url directly

### ISSUE THREAD

**Issue by fengmk2** [cnpm/mirrors#43]
dont use tmp download

**Comment by fengmk2** [comment]
https://github.com/cnpm/mirrors/blob/master/controllers/dist.js#L146 can't remove file...

![image](https://cloud.githubusercontent.com/assets/156269/6480378/14de1d68-c28e-11e4-83d7-b80d1d5dc890.png)

![image](https://cloud.githubusercontent.com/assets/156269/6480383/210fc8b6-c28e-11e4-9d66-648e19add290.png)

**Comment by fengmk2** [comment]
![image](https://cloud.githubusercontent.com/assets/156269/6480401/49ca927c-c28e-11e4-9d8d-0da0ad60ccad.png)

**Comment by dead-horse** [comment]
你在做了么？

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmjs.org/wiki/NFS-Guide
