### ISSUE TITLE
Feature: Add Chromium source code mirror

### ISSUE THREAD

**Issue by hokein** [cnpm/mirrors#51]
Hi @fengmk2 @dead-horse ,

Taobao's npm have already provided `electron` and `atom` mirrors.

Could you please also add the [`chromium-source-tarball`](https://github.com/zcbenz/chromium-source-tarball) mirror? This repo contains the Chromium source code for each release and is used in `electron` development. And I think Chinese `electron` developers will be quite benefited from it. Thanks a lot!

/cc @zcbenz

**Comment by fengmk2** [comment]
OK, I will add @zcbenz's chromium

**Comment by fengmk2** [comment]
![image](https://cloud.githubusercontent.com/assets/156269/8618665/de2afb46-2742-11e5-9b18-accfd9718b1c.png)

500MB ... too large to upload it to our China cloud store.

**Comment by fengmk2** [comment]
tar too big, close for now.
