### ISSUE TITLE
mirror fsevents

### ISSUE THREAD

**Issue by fengmk2** [cnpm/mirrors#76]
https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.2/fse-v1.0.2-node-v46-darwin-x64.tar.gz

webpack need it..

**Comment by fengmk2** [comment]
need mapbox/node-pre-gyp#170 merged.

```bash
$ npm install fsevents \
  --fsevents_binary_host_mirror=http://npm.taobao.org/mirrors/fsevents/
```

**Comment by pbdm** [comment]
@fengmk2 `fsevents`'s module_name is `fse`, so I think we need to use
~~~
$ npm install fsevents \
  --fse_binary_host_mirror=https://npm.taobao.org/mirrors/fsevents/
~~~
