### ISSUE TITLE
mirror mongodb

### ISSUE THREAD

**Issue by fengmk2** [cnpm/mirrors#93]

**Comment by nightink** [comment]
配置类似 https://github.com/cnpm/mirrors/blob/master/config/index.js#L184 这个 
把 disturl 修改成 https://github.com/mongodb/mongo/releases 这个就可以了？

**Comment by nightink** [comment]
我可以尝试一下～～ :jack_o_lantern:

**Comment by nightink** [comment]
linux https://www.mongodb.org/dl/linux/x86_64-rhel62
osx https://www.mongodb.org/dl/osx
win32 https://www.mongodb.org/dl/win32

**Comment by fengmk2** [comment]
@nightink 来，我指派给你。

**Comment by nightink** [comment]
@fengmk2 好了

我会尽快处理掉～

**Comment by fengmk2** [comment]
@nightink 这周能完成么？

**Comment by nightink** [comment]
@fengmk2 嗯 周天我来试试 应该需要写个 MongoSyncer

**Comment by nightink** [comment]
@fengmk2 对了 我咋测试 本地 runner  sync 看看数据能不能拿到吗  （小白问题

**Comment by nightink** [comment]
晚上或者明天提个 PR 出来，https://github.com/cnpm/mirrors/tree/master/test/sync 参考这个写单测

**Comment by nightink** [comment]
![image](https://cloud.githubusercontent.com/assets/2972143/14580529/5e611448-0402-11e6-96a0-a08aca11a2cb.png)

node-pre-gyp 没代理到 https://npm.taobao.org/mirrors/sqlite3/

**Comment by fengmk2** [comment]
@nightink 重新安装 cnpm 或者 tnpm
